# Generated by Django 5.2.14 on 2026-05-19 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(help_text='국회 API BILL_ID', max_length=50, unique=True)),
                ('bill_no', models.CharField(help_text='의안번호', max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('proposer', models.CharField(max_length=200)),
                ('committee', models.CharField(blank=True, default='', max_length=100)),
                ('stage', models.CharField(choices=[('proposed', '발의'), ('committee', '위원회 심사'), ('plenary', '본회의 상정'), ('passed', '통과 · 공포')], default='proposed', max_length=20)),
                ('proposed_at', models.DateField()),
                ('detail_link', models.URLField(blank=True, default='', max_length=500)),
                ('age', models.IntegerField(default=22, help_text='국회 대수')),
                ('view_count', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bill',
                'ordering': ['-proposed_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=30)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'category',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='BillSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_1', models.TextField()),
                ('summary_2', models.TextField(blank=True, default='')),
                ('summary_3', models.TextField(blank=True, default='')),
                ('impact', models.TextField(blank=True, default='')),
                ('sentiment', models.IntegerField(default=0, help_text='0-100')),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='bills.bill')),
            ],
            options={
                'db_table': 'bill_summary',
            },
        ),
        migrations.CreateModel(
            name='BillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_categories', to='bills.bill')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_categories', to='bills.category')),
            ],
            options={
                'db_table': 'bill_category',
                'unique_together': {('bill', 'category')},
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='categories',
            field=models.ManyToManyField(related_name='bills', through='bills.BillCategory', to='bills.category'),
        ),
        migrations.CreateModel(
            name='SimilarBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date', models.CharField(blank=True, default='', max_length=20)),
                ('stage_label', models.CharField(blank=True, default='', max_length=30)),
                ('source_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_bills', to='bills.bill')),
            ],
            options={
                'db_table': 'similar_bill',
            },
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['-proposed_at'], name='idx_bill_proposed_at'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['stage'], name='idx_bill_stage'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['age'], name='idx_bill_age'),
        ),
        migrations.AddIndex(
            model_name='similarbill',
            index=models.Index(fields=['source_bill'], name='idx_sb_source'),
        ),
    ]
