# Generated by Django 5.2.15 on 2026-06-24 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_bill_result_status_bill_result_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='similarbill',
            options={'ordering': ['rank', '-score', 'title']},
        ),
        migrations.AddField(
            model_name='similarbill',
            name='generated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='similarbill',
            name='method',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='similarbill',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='similarbill',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='similarbill',
            name='target_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_by_bills', to='bills.bill'),
        ),
        migrations.AddIndex(
            model_name='similarbill',
            index=models.Index(fields=['source_bill', 'rank'], name='idx_sb_source_rank'),
        ),
    ]
