# Generated by Django 5.2.14 on 2026-06-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'account',
                'ordering': ['idx'],
            },
        ),
    ]
