# Generated by Django 5.2.14 on 2026-05-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='snapshot',
            field=models.JSONField(blank=True, help_text='질문 구조화 분석 결과 스냅샷', null=True),
        ),
    ]
