# Generated by Django 5.2.15 on 2026-06-23 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bills', '0003_single_running_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('bill', models.ForeignKey(db_column='bill_id', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='bills.bill', to_field='bill_id')),
                ('user', models.ForeignKey(db_column='user_idx', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.account')),
            ],
            options={
                'db_table': 'post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_idx', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='posts.comment')),
                ('user', models.ForeignKey(db_column='user_idx', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.account')),
                ('post', models.ForeignKey(db_column='post_idx', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
            options={
                'db_table': 'comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['bill', '-created_at'], name='idx_post_bill_created'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', '-created_at'], name='idx_post_user_created'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='idx_comment_post_time'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'created_at'], name='idx_comment_parent_time'),
        ),
    ]
